apiVersion: v1
kind: Secret
metadata:
  name: otel-monitor-secret
  namespace: monitoring
type: Opaque
stringData:
  APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=b20e11c7-02f7-46f9-8d90-a69a7795d181;IngestionEndpoint=https://canadacentral-1.in.applicationinsights.azure.com/;LiveEndpoint=https://canadacentral.livediagnostics.monitor.azure.com/;ApplicationId=092564b9-3de9-4015-aee1-b81629b74388"
